name: Auto-merge Dependabot minor/patch/security updates

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: squash
          # Only merge if PR has one of these labels and does NOT have 'major'
          # This is a filter expression supported by the automerge-action
          # See: https://github.com/pascalgn/automerge-action#options
          labels: 'patch,minor,security'
          # Do not merge if the PR has the 'major' label
          # The action will skip PRs with the 'major' label